### ISSUE TITLE
Why is there no 0.7.0 release?

### ISSUE THREAD

**Issue by martinmalek** [gini/dropwizard-gelf#11]
Why is the 0.7.0 version not released?

**Comment by joschi** [comment]
dropwizard-gelf 0.6.0 is compatible with Dropwizard 0.7.x.

Starting with dropwizard-gelf 0.8.0-1 the versioning scheme has been updated to match Dropwizard releases.

**Comment by martinmalek** [comment]
You are missing my point. 0.7.0 is not part of https://github.com/gini/dropwizard-gelf/releases. Could you please tag it? Right now gradle resolves it to an incompatibl 0.8.x version. :)

**Comment by joschi** [comment]
There is no dropwizard-gelf 0.7.0 release.

**Comment by martinmalek** [comment]
Could there be a 0.7.0 so we can get logback-gelf 0.12 in a DW 0.7.x setup?

**Comment by Moocar** [comment]
Heads up, I'm actively working on a new logback-gelf 0.13 release. Hopefully will happen in the next couple of weeks

**Comment by joschi** [comment]
@martinmalek I've released dropwizard-gelf 0.7.0.
@Moocar Cool, thanks for the heads-up!

**Comment by martinmalek** [comment]
Thumbs up! :+1:
