### ISSUE TITLE
0.8.1 dropwizard

### ISSUE THREAD

**Issue by sheldon-sminq** [gini/dropwizard-gelf#12]
Does this work with dropwizard 0.8.1? I have configured but i dont get any errors and no logs are visible in graylog2

**Comment by Trundle** [comment]
Yes, dropwizard-gelf should work with dropwizard 0.8.1. Note that it currently only supports UDP as transport, hence your Graylog instance is required to have a running UDP input.

**Comment by Trundle** [comment]
I'm closing this issue. Feel free to reopen if you have more questions.
