### ISSUE TITLE
Dropwizard-gelf should work on TCP

### ISSUE THREAD

**Issue by sandeepkaul** [gini/dropwizard-gelf#16]
Currently since it works on UDP, it's a problem since some production environments have UDP Disabled.
Can we have it working on TCP?

**Comment by Trundle** [comment]
Hi,

I agree that being able to use other transports that UDP would be useful. Unfortunately, I cannot make any guarantee that we will be working on that soon(-ish). Please feel free to provide a pull request.

On a somewhat related note, dropwizard-gelf's underlying library [logback-gelf](https://github.com/Moocar/logback-gelf) is nowadays officially unmaintained. In the long term, it would probably make sense to migrate to some other library such as [logstash-gelf](https://github.com/mp911de/logstash-gelf) (despite its confusing name, it provides a `GelfLogbackAppender`).

Cheers,
Andreas
