### ISSUE TITLE
Docs reference unreleased version

### ISSUE THREAD

**Issue by mnazbro** [gini/dropwizard-gelf#21]
In the README.md, there is a reference to a `dropwizard-gelf` which is version `1.0.0-1`. 

Here's the snippet that says it:
```
<dependency>
  <groupId>net.gini.dropwizard</groupId>
  <artifactId>dropwizard-gelf</artifactId>
  <version>1.0.0-1</version>
</dependency>
```

Has this version been released or is it just a typo?

**Comment by Trundle** [comment]
Hi,

the referenced version is indeed not released yet. The latest version of dropwizard-gelf is `0.9.2-5` as indicated by the maven-central badge at the top of the README. The `master` branch already includes the changes for the next release which targets Dropwizard 1.0. The branch for releases that work together with Dropwizard 0.9.x is [0.9.x](https://github.com/gini/dropwizard-gelf/tree/0.9.x), which should contain the correct version in [its README.](https://github.com/gini/dropwizard-gelf/blob/0.9.x/README.md).

In general, dropwizard-gelf follows the version scheme `<dropwizard version>-<dropwizard-gelf version>` (i.e. the current release `0.9.2-5` is the fifth release of dropwizard-gelf for Dropwizard `0.9.2`).

**Comment by Trundle** [comment]
I'm closing this issue. Feel free to re-open if you have further questions or suggestions.
