### ISSUE TITLE
dropwizard-gelf breaks directly writing to ServletOutputStream using WriteListener

### ISSUE THREAD

**Issue by madmuffin1** [gini/dropwizard-gelf#27]
Since `net.gini.dropwizard.gelf.filters.GelfLoggingFilter.CountingServletOutputStream#setWriteListener` is not implemented, any endpoint that directly writes to the OutputStream using a WriteListener causes an error 500, as soon as this filter is installed.

Such implementation is useful when streaming large amounts of data.

Such a response will most probably not have a `Content-Length` header, so the logger will probably also not know the size of the response

See https://github.com/madmuffin1/dropwizard-gelf-issue27 for a sample project that reproduces the problem.

**Comment by madmuffin1** [comment]
@Trundle @joschi can I get a feedback from either of you on this?

**Comment by Trundle** [comment]
Thank you so much for the issue report and the sample project.

I followed a slightly different approach in #29 than your suggested solution, in case there is another wrapper around the `HttpOutput` (for example another filter).

Once one of my colleagues or @joschi reviewed the merge request, I can release another version (probably Monday or Tuesday).
